package com.huttger.joshua.story;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/story") // This means URL's start with /demo (after Application path)
public class StoryStoreController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private StoryRepository storyRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewStory (@RequestParam String title
			, @RequestParam String contents) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Story n = new Story();
		n.setTitle(title);
		n.setContents(contents);
		storyRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Story> getAllStories() {
		// This returns a JSON or XML with the users
		return storyRepository.findAll();
	}
}
